cc_binary(
    name = "async_client",
    srcs = ["demo/async/client.c"],
    deps = [
        ":nng",
    ]
)

cc_binary(
    name = "async_server",
    srcs = ["demo/async/server.c"],
    deps = [
        ":nng",
    ]
)

cc_binary(
    name = "http_client",
    srcs = ["demo/http_client/http_client.c"],
    deps = [
        ":nng",
    ]
)

cc_binary(
    name = "raw",
    srcs = ["demo/raw/raw.c"],
    deps = [
        ":nng",
    ]
)

cc_binary(
    name = "reqrep",
    srcs = ["demo/reqrep/reqrep.c"],
    deps = [
        ":nng",
    ]
)

cc_binary(
    name = "rest_server",
    srcs = ["demo/rest/server.c"],
    deps = [
        ":nng",
    ]
)
