cc_binary(
    name = "async_client",
    srcs = ["async/client.c"],
    deps = [
        "//:nng",
    ]
)

cc_binary(
    name = "async_server",
    srcs = ["async/server.c"],
    deps = [
        "//:nng",
    ]
)

cc_binary(
    name = "http_client",
    srcs = ["http_client/http_client.c"],
    deps = [
        "//:nng",
    ]
)

cc_binary(
    name = "raw",
    srcs = ["raw/raw.c"],
    deps = [
        "//:nng",
    ]
)

cc_binary(
    name = "reqrep",
    srcs = ["reqrep/reqrep.c"],
    deps = [
        "//:nng",
    ]
)

cc_binary(
    name = "rest_server",
    srcs = ["rest/server.c"],
    deps = [
        "//:nng",
    ]
)
